# This workflow is managed by gh actions-lock.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1

    - name: Set up Node.js
      uses: actions/setup-node@v7.0.0
      with:
        node-version: '20'

    - name: Install dev dependencies
      run: npm ci

    - name: Install just
      uses: taiki-e/install-action@v2.85.7
      with:
        tool: just

    - name: Test Component
      run: just test
